openapi: 3.1.0
info:
  title: lab09_API_endpoints
  version: 1.0.0
  description: API for managing products
servers:
  - url: http://localhost:4000
paths:
  /api/products:
    get:
      summary: Return all products with optional filtering
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{id}:
    get:
      summary: Return a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Product updated successfully
  /api/products/batch:
    get:
      summary: Return a batch of products by IDs
      parameters:
        - name: ids
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Batch of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: string
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: number
        productCategory:
          type: string
        imageUrls:
          type: array
          items:
            type: string
            format: uri
    ProductInput:
      type: object
      properties:
        productName:
          type: string
        productDescription:
          type: string
        productPrice:
          type: number
        productCategory:
          type: string
        imageUrls:
          type: array
          items:
            type: string
            format: uri

  
