### Update Product (PUT)
PUT http://localhost:4000/api/products/prod_21
Content-Type: application/json

{
  "productName": "iPhone 17 Promax",
  "productDescription": "Updated product description with more details",
  "productPrice": "1999.99",
  "productCategory": "Electronics",
  "imageUrls": [
    "https://example.com/images/iPhone.png",
    "https://example.com/images/iPhone1.png",
    "https://example.com/images/iPhone2.png",
    "https://example.com/images/iPhone3.png",
    "https://example.com/images/iPhone4.png",
    "https://example.com/images/iPhone5.png"
  ]
}

